# Generated by Django 5.2.7 on 2025-10-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_immersivehero_immersivemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immersivemedia',
            name='hero',
        ),
        migrations.DeleteModel(
            name='ImmersiveHero',
        ),
        migrations.DeleteModel(
            name='ImmersiveMedia',
        ),
    ]
