# Generated by Django 5.2.7 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link', null=True),
        ),
    ]
