# Generated by Django 5.2.7 on 2025-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_exhibition_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='exhibition/videos/'),
        ),
    ]
