# Generated by Django 5.2.7 on 2025-10-16 16:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_exhibition_video_url_exhibition_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
