# Generated by Django 5.2.7 on 2025-10-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_exhibition_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'verbose_name_plural': 'Exhibitions'},
        ),
    ]
