# Generated by Django 5.2.7 on 2025-10-16 12:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=100)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('purchase', 'Purchase Interest'), ('exhibition', 'Exhibition Inquiry'), ('commission', 'Commission Request'), ('other', 'Other')], default='general', help_text='Type of inquiry', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject of the inquiry', max_length=100)),
                ('message', models.TextField(help_text='Detailed information')),
                ('artwork_title', models.CharField(blank=True, help_text='Title of artwork if inquiry is about a specific piece', max_length=100, null=True)),
                ('artwork_reference', models.CharField(blank=True, help_text='Artwork ID or reference number', max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, help_text='Has this inquiry been read?')),
                ('is_responded', models.BooleanField(default=False, help_text='Has this inquiry been responded to?')),
                ('response_notes', models.TextField(blank=True, help_text='Internal notes for follow-up', null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='email', help_text='Your preferred method of contact', max_length=10)),
            ],
            options={
                'verbose_name': 'Contact Requests',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
